name: NPM Package ChangeLog URL
description: Comment ChangeLog URLs of updated NPM Packages
author: kzkn
inputs:
  githubToken:
    required: true
  npmToken:
    required: true
  yarnLockPath:
    default: 'yarn.lock'
runs:
  using: 'node12'
  main: 'dist/index.js'
