name: NPM Package ChangeLog URL
description: Comment ChangeLog URLs of updated NPM Packages
author: kzkn
inputs:
  githubToken:
    required: true
  npmToken:
    required: true
  lockPath:
    default: "yarn.lock"
  onlySpecifiedPackages:
    type: boolean
    default: false
runs:
  using: "node16"
  main: "dist/index.js"
